version: '3.9'

volumes:
  postgres-demo-data:

services:
  demo-db:
    container_name: demo-db
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-demo-data:/var/lib/postgresql/data
    networks:
      - demo-net
  demo-liquibase:
    container_name: demo-liquibase
    depends_on:
      - demo-db
    image: liquibase/liquibase
    command: --url=jdbc:postgresql://demo-db:5432/postgres?user=postgres&password=postgres --changeLogFile=changelog.xml update
    volumes:
      - ./src/main/resources/db/changelog/changelog.xml:/liquibase/changelog.xml
      - ./src/main/resources/db/scripts:/liquibase/scripts
    networks:
      - demo-net
  app:
    container_name: demo-app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://demo-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - demo-db
      - demo-liquibase
    networks:
      - demo-net
networks:
  demo-net: