CREATE TABLE "user" (
    ID BIGSERIAL PRIMARY KEY UNIQUE,
    NAME VARCHAR(500),
    DATE_OF_BIRTH DATE,
    PASSWORD VARCHAR(500) CONSTRAINT password_length CHECK (char_length(PASSWORD) >= 8 AND char_length(PASSWORD) < 500)
);

CREATE TABLE "account" (
    ID BIGSERIAL PRIMARY KEY UNIQUE,
    USER_ID BIGINT REFERENCES "user" (ID) UNIQUE,
    BALANCE DECIMAL CONSTRAINT account_balance CHECK (BALANCE >= 0.0),
    INITIAL_BALANCE DECIMAL CONSTRAINT account_initial_balance CHECK (INITIAL_BALANCE >= 0.0)
);

CREATE TABLE "email_data" (
    ID BIGSERIAL PRIMARY KEY UNIQUE,
    USER_ID BIGINT REFERENCES "user" (ID),
    EMAIL VARCHAR(200) UNIQUE
);

CREATE TABLE "phone_data" (
    ID BIGSERIAL PRIMARY KEY UNIQUE,
    USER_ID BIGINT REFERENCES "user" (ID),
    PHONE VARCHAR(13) UNIQUE
);